#!/bin/bash
#SBATCH --job-name=radiomics
#SBATCH --time=02:00:00
#SBATCH --cpus-per-task=1
#SBATCH --mem=8G
#SBATCH --output=logs/radiomics_%a_%j.out
#SBATCH --error=logs/radiomics_%a_%j.err

# SLURM wrapper for radiomics feature extraction
# Run find_radiomics_subjects.sh first to generate radiomics_subjects.txt

# ============================================================================
# CONFIGURATION
# ============================================================================

# FreeSurfer subjects directory
SUBJECTS_DIR="/data/projects/CSC/data/XTC/next_xtc/derivatives_unzipped"

# Output directory for radiomics results
OUTPUT_DIR="/data/projects/CSC/code/XTC/05_Radiomics_v2/radiomics_results"

# Subject list file (generated by find_radiomics_subjects.sh)
SUBJECT_LIST="${OUTPUT_DIR}/radiomics_subjects.txt"

# Path to Python script
PYTHON_SCRIPT="extract_radiomics.py"

# Activate conda environment
source $(conda info --base)/etc/profile.d/conda.sh
conda activate python

# ============================================================================
# READ SUBJECT FROM LIST
# ============================================================================

# Create output directory if it doesn't exist
mkdir -p ${OUTPUT_DIR}
mkdir -p logs

# Check if subject list exists
if [ ! -f "${SUBJECT_LIST}" ]; then
    echo "ERROR: Subject list not found: ${SUBJECT_LIST}"
    echo "Please run find_radiomics_subjects.sh first"
    exit 1
fi

# Get the line corresponding to this array task (1-indexed)
LINE_NUM=$((SLURM_ARRAY_TASK_ID + 1))
SUBJECT_ID=$(sed -n "${LINE_NUM}p" ${SUBJECT_LIST})

if [ -z "${SUBJECT_ID}" ]; then
    echo "ERROR: No subject found for array index ${SLURM_ARRAY_TASK_ID}"
    exit 1
fi

echo "=========================================="
echo "Radiomics Feature Extraction"
echo "Subject: ${SUBJECT_ID}"
echo "Job ID: ${SLURM_JOB_ID}"
echo "Array Task ID: ${SLURM_ARRAY_TASK_ID}"
echo "=========================================="

# ============================================================================
# RUN RADIOMICS EXTRACTION
# ============================================================================

# Check if results already exist
OUTPUT_FILE="${OUTPUT_DIR}/${SUBJECT_ID}_radiomics.json"
if [ -f "${OUTPUT_FILE}" ]; then
    echo "Results already exist for ${SUBJECT_ID}, skipping"
    echo "To reprocess, delete: ${OUTPUT_FILE}"
    exit 0
fi

# Run Python script
python ${PYTHON_SCRIPT} ${SUBJECTS_DIR} \
    --subject ${SUBJECT_ID} \
    --output-dir ${OUTPUT_DIR}

if [ $? -eq 0 ]; then
    echo "=========================================="
    echo "SUCCESS: Radiomics extraction complete"
    echo "Output: ${OUTPUT_FILE}"
    echo "=========================================="
    exit 0
else
    echo "=========================================="
    echo "ERROR: Radiomics extraction failed"
    echo "Check log for details"
    echo "=========================================="
    exit 1
fi
